config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  # https://stackoverflow.com/questions/5690406/rails-using-devise-with-single-table-inheritance
  devise_for :users, :controllers => { :sessions => 'sessions' }
  devise_for :administrators, :teachers, :students, :skip => :sessions, :controllers => { :registrations => 'registrations' }

  resources :users, only: [:approve] do 
    patch 'approve', on: :member
  end
  resources :administrators, only: [:show] do 
    get 'home', on: :member
  end 
  resources :teachers, only: [:show] do 
    get 'home', on: :member
  end 
  resources :students, only: [:show] do 
    get 'home', on: :member
  end 

  resources :subjects do 
    resources :seminars
    resources :attendees
    resources :tests do
      resources :results
    end
  end
  
end

app/models/administrator.rb
class Administrator < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :subject
  belongs_to :user, foreign_key: 'student_id'
  validates :subject, uniqueness: { scope: :user }
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :test
  belongs_to :student, :class_name => "User", foreign_key: 'student_id'
  belongs_to :teacher, :class_name => "User", foreign_key: 'teacher_id'
end

app/models/seminar.rb
class Seminar < ApplicationRecord
    belongs_to :subject
    belongs_to :user, foreign_key: 'teacher_id'
    validates :subject, uniqueness: { scope: :user }
end

app/models/student.rb
class Student < User
  has_many :attendees
  has_many :subjects, through: :attendees
  has_many :results

  def performance_subject(subject)
    subject_results = results.where(test: subject.tests)
    performance_tests subject_results
  end

  def performance_subjects
    performance_tests results
  end
  
  def performance_tests(test_results)
    unless test_results.empty?
      test_results.sum(&:mark) / test_results.count
    end
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :seminars, dependent: :destroy
  has_many :teachers, through: :seminars, source: :user
  has_many :attendees, dependent: :destroy
  has_many :students, through: :attendees, source: :user
  has_many :tests
end

app/models/teacher.rb
class Teacher < User
  has_many :seminars
  has_many :subjects, through: :seminars
  has_many :students, through: :subjects

  def students_performance
    unless students.empty?
      students.sum(&:performance_subjects) / students.count
    end
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :subject
  has_many :results
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def active_for_authentication? 
    super && approved? 
  end 
  
  def inactive_message 
    approved? ? super : :not_approved
  end

  def full_name
    first_name + " " + last_name
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include Roles

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :approved])
  end

  def after_sign_in_path_for(user)
    home_path_for user
  end


end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def new
    @subject = Subject.find(params[:subject_id])
    student_ids = Attendee.where(subject: @subject).pluck(:student_id)
    @students = Student.where.not(id: student_ids).and(Student.where(approved: true))
    @attendee = authorize Attendee.new
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @attendee = authorize @subject.attendees.create(attendee_params)
    
    if @attendee.save!
      redirect_to @subject
    else 
      render :new
    end 
  end

  private
    def attendee_params
      params.require(:attendee).permit(:subject_id, :student_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Roles

  def index
    if current_user
      redirect_to home_path_for current_user
    end
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def new
    @subject = Subject.find(params[:subject_id])
    @test = Test.find(params[:test_id])
    @student = Student.find(params[:student_id])
    @result = authorize Result.new(test_id: params[:test_id])
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @test = Test.find(params[:test_id])
    @student = Student.find(result_params[:student_id])
    @result = authorize @test.results.create(result_params.merge(teacher_id: current_user.id))
    
    if @result.save!
      redirect_to subject_test_path(@subject, @test)
    else 
      render :new
    end 
  end

  private
    def result_params
      params.require(:result).permit(:test_id, :teacher_id, :student_id, :mark)
    end

end

app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController

  def new
    @subject = Subject.find(params[:subject_id])
    teacher_ids = Seminar.where(subject: @subject).pluck(:teacher_id)
    @teachers = Teacher.where.not(id: teacher_ids).and(Teacher.where(approved: true))
    @seminar = authorize Seminar.new
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @seminar = authorize @subject.seminars.create(seminar_params)
    
    if @seminar.save!
      redirect_to @subject
    else 
      render :new
    end 
  end

  private
    def seminar_params
      params.require(:seminar).permit(:subject_id, :teacher_id)
    end

end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def create
    rtn = super
    sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
    rtn
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = authorize Student.find(params[:id])
  end

  def home
    @student = authorize Student.find(params[:id])
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  include Roles

  def index
    @subjects = authorize Subject.all
  end

  def show
    @subject = authorize Subject.find(params[:id])
    @show_add_teacher = is_admin? current_user
    @show_add_test = is_teacher? current_user
    @show_add_student = is_teacher? current_user
  end

  def new
    @subject = authorize Subject.new
  end

  def create
    @subject = authorize Subject.new(subject_params)
    
    if @subject.save
      redirect_to @subject
    else 
      render :new
    end 
  end

  private
    def subject_params
      params.require(:subject).permit(:name, :description)
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def show
    @teacher = authorize Teacher.find(params[:id])
  end
  
  def home
    @teacher = authorize Teacher.find(params[:id])
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def show
    @subject = Subject.find(params[:subject_id])
    @test = authorize Test.find(params[:id])
    @students = @subject.students
    @results = Result.where(test: params[:id]).index_by(&:student_id)
  end

  def new
    @subject = Subject.find(params[:subject_id])
    @test = authorize Test.new
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @test = authorize @subject.tests.create(test_params)
    
    if @test.save!
      redirect_to @subject
    else 
      render :new
    end 
  end

  private
    def test_params
      params.require(:test).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def approve
    @user = User.find(params[:id])
    @user.update(approved: true)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendees/_form.html.slim
= form_with model: [ @subject, @attendee ] do |form|

  div 
    p Select the student:
    = collection_select :attendee, :student_id, @students, :id, :full_name, prompt: true 
  br /

  div
    = form.submit 

app/views/attendees/new.html.slim
= render "home/header"

h1 #{@subject.name} - New student

= render "form", teachers: @teachers

app/views/results/_form.html.slim
= form_with model: [ @subject, @test, @test.results.build ] do |form|

  div
    = form.label :mark 
    br
    = form.number_field :mark, step: :any
    br  
      - result.errors.full_messages_for(:mark).each do |message| 
        div = message 

  = form.hidden_field :student_id, :value => params[:student_id]
  
  div
    = form.submit 

app/views/results/new.html.slim
= render "home/header"

h1 = @test.name
h2 = @student.full_name
= render "form", result: @result

app/views/seminars/_form.html.slim
= form_with model: [ @subject, @seminar ] do |form|

  div 
    p Select the teacher:
    = collection_select :seminar, :teacher_id, teachers, :id, :full_name, prompt: true 
  br /

  div
    = form.submit 

app/views/seminars/new.html.slim
= render "home/header"

h1 #{@subject.name} - New teacher

= render "form", teachers: @teachers

app/views/students/_list.html.slim
.ul
  - students.each do |student|
    li = link_to student.full_name, student

app/views/students/home.html.slim
= render "home/header"

h1 Dashboard
= render "users/profile", user: @student

hr 

app/views/students/show.html.slim
= render "home/header"

h1 Dashboard
= render "users/profile", user: @student

hr 

app/views/subjects/_form.html.slim
= form_with model: subject do |form|

  div
    = form.label :name 
    br
    = form.text_field :name 
    br  
      - subject.errors.full_messages_for(:name).each do |message| 
        div = message 

  div
    = form.label :description 
    br
    = form.text_area :description 
    br  
      - subject.errors.full_messages_for(:name).each do |message| 
        div = message 
  
  div
    = form.submit 

app/views/subjects/edit.html.slim
= render "home/header"

h1 Edit Subject

= render "form", subject: @subject

app/views/subjects/new.html.slim
= render "home/header"

h1 New Subject

= render "form", subject: @subject

app/views/subjects/show.html.slim
= render "home/header"

h1 #{@subject.name}
p #{@subject.description}


div style="float:left; width:33%;"
  h2 Teachers 
  - if @subject.seminars.empty? 
    p There are no teachers for this subject yet
  - else 
    = render "teachers/list", teachers: @subject.teachers
  - if @show_add_teacher
    p #{link_to "Add Teacher", new_subject_seminar_path(@subject)}


div style="float:left; width:34%;"
  h2 Tests
  - if @subject.tests.empty? 
    p There are no tests for this subject yet
  - else 
    = render "tests/list", tests: @subject.tests
  - if @show_add_test
    p #{link_to "Add Test", new_subject_test_path(@subject)}

div style="float:left; width:33%;"
  h2 Students 
  - if @subject.attendees.empty? 
    p There are no students for this subject yet
  - else 
    = render "students/list", students: @subject.students
  - if @show_add_student
    p #{link_to "Add Student", new_subject_attendee_path(@subject)}

app/views/teachers/_list.html.slim
.ul
  - teachers.each do |teacher|
    li = link_to teacher.full_name, teacher

app/views/teachers/home.html.slim
= render "home/header"

h1 Dashboard
= render "users/profile", user: @teacher

hr 

div
  h2 Subjects
  - unless @teacher.seminars.empty?
    - @teacher.seminars.each do |seminar|
      h3 = link_to seminar.subject.name, seminar.subject
      - unless seminar.subject.attendees.empty?
        h4 Students
        table border = "1" style="width:60%"
          tr 
            th style="width:60%" Name 
            th style="width:40%" Students' performance  
          - seminar.subject.students.each do |student|
            tr
              td = link_to student.full_name, student
              td style="text-align: center;" 
                = student.performance_subject(seminar.subject).nil? ? "-" : student.performance_subject(seminar.subject).round(2)
      p #{link_to "Add Student", new_subject_attendee_path(seminar.subject)}
  br/

app/views/teachers/show.html.slim
= render "home/header"

h1 Dashboard
= render "users/profile", user: @teacher

hr 

app/views/users/_profile.html.slim
h2 #{user.full_name}
p Role: #{user.type}
p Email: #{user.email}